### ISSUE TITLE
Do we need a longhand for initial states?

### ISSUE THREAD

**Issue by mirisuzanne** [tabatkins/css-toggle#1]
In the tab-group demo, in order to set an active initial state on the first tab, we repeat the entire `toggle` declaration with a minor change ([line 455](https://github.com/tabatkins/css-toggle/blob/8a57731d84eecab6de3697a2100d399a80aa4627/index.bs#L455)):

```css
panel-tab {
  /* Each tab creates a sticky toggle,
    opts into the group,
    and declares itself a toggle activator */
  toggle: --tab 1 group sticky;
}

panel-tab:first-of-type {
  /* The first tab also sets its initial state
    to be active */
  toggle: --tab 1/1 group sticky;
}
```

I wonder if we want some form of `toggle-initial-state` longhand. It does seem like there are many instances where we might want to set/cascade the state independent from the rest of the toggle definition -- like a non-exclusive accordion set, with one or multiple starting open; a todo list with several items checked, etc.

**Comment by mirisuzanne** [comment]
I understand that initial state has to be established at toggle-creation time to avoid loops -- but I think we already have to solve that problem in handling eg:

```css
item {
  toggle: --tab 2;
}

item:checked(--tab 2) {
  toggle: --tab 1;
}
```
