### ISSUE TITLE
Allow creating toggle-roots without implicit toggling

### ISSUE THREAD

**Issue by flackr** [tabatkins/css-toggle#13]
I think that it will be useful to create `toggle-root`s at a high level in a component with specific `toggle-trigger` further down the DOM. When doing this, it would be nice if the `toggle-root` could be specified to not have any implicit activation. E.g.

```css
body {
  toggle-root: state;
}
.save {
  toggle-state: state 1; /* save button transitions to loading state */
}
body .loading-spinner:toggle(state 1) {
  display: block;
}
```

Unless I'm mistaken, I don't think there's any way in css to prevent the toggle-root from having implicit activation behavior currently though.
