### ISSUE TITLE
allow connecting more distant elements to the same toggle

### ISSUE THREAD

**Issue by dbaron** [tabatkins/css-toggle#46]
There are use cases for connecting more distant elements with the same toggle.  For example, typical tab component markup might look something like (in very abbreviated form, with names I just made up):

```xml
<tab-view>
  <tab-strip>
    <tab/>
    <tab/>
    <tab/>
  </tab-strip>
  <panel-set>
    <panel/>
    <panel/>
    <panel/>
  </panel-set>
</tab-view>
```

With this sort of markup, it's hard to model the three tabs using three separate toggles, each with two states, connected into a toggle group.  (They could be modeled as a single 3-state toggle, but that has disadvantages, particularly when reordering, adding, or removing tabs.)

It would be desirable to have a way to use a group of 2-state toggles for markup like this.

**Comment by dbaron** [comment]
cc @bramus

**Comment by bramus** [comment]
Looking at [the component gallery for tabs](https://component.gallery/components/tabs/), many implementations use a structure where the tabs and panels are no siblings of each other indeed.

With the current specced version it’s pretty difficult to implement this. The needed CSS for the example above to work, would look like this:

```css
tab-view {
    toggle-root: tab 3 at 1;
}

tab:nth-child(1) {
    toggle-trigger: tab 1;
}
tab:nth-child(2) {
    toggle-trigger: tab 2;
}
tab:nth-child(3) {
    toggle-trigger: tab 3;
}

tab:nth-child(1):toggle(tab 1),
tab:nth-child(2):toggle(tab 2),
tab:nth-child(3):toggle(tab 3) {
    background-color: lightgray;
}

panel {
    display: none;
}
tab-view:toggle(tab 1) panel:nth-child(1),
tab-view:toggle(tab 2) panel:nth-child(2),
tab-view:toggle(tab 3) panel:nth-child(3) {
    display: block;
}
```

This does not scale, as it requires extra code for each tab that gets added. It also relies on counting DOM nodes to make it work.

Maybe some extension to `toggle-visibility` could make this easier, where it would also take the active toggle value into account.

A similar use-case would be a lightbox implementation where thumbnails somewhere in the DOM control the contents of a dialog element, which could be included somewhere else in the DOM.

**Comment by tabatkins** [comment]
Yeah, the "groups tabs + grouped panels" example absolutely needs something here, and there are additional cases where the *standard* button might be grouped usefully to see the toggle, but you want the ability to have another button elsewhere that'll also trigger it.

So I've been giving this some thought. Making it work *fully* ends up being *very* difficult, but I think I've got an approach that works with minimal user-facing complexity (and hopefully manageable impl complexity).

First, the requirements. We want "grouped tabs" to be as close to equivalent in functionality and ease-of-use as "alternating tabs" (where tabs and the panels they control are next to each other). This means, specifically:

1. Any number of tabs can be in a group. Adding or removing tabs should require minimal editing; ideally *zero* changes to the stylesheet, but a small amount of editing in attributes is permissible.
2. The toggle properties should be as reusable as possible, ideally all using the same generic name for their toggle.
3. :toggle() selectors must be able to target both the tab and the panel, in a reusable fashion (using a single generic name for the toggle).
4. The tabs component as a whole must be usable repeatedly on a page without each component having to care about anything outside of itself; any names used are "scoped" to the component rather than global.

-----

My proposal is that we create a new bit of persistent state, the "toggle share". An element can declare that it's sharing toggles under a chosen name, optionally scoped to a group name, and declare zero or more of its own toggles that should be shared to the group. Every element using the same share name (and in the same group) acts as if all the shared toggles among the entire group are present on the element itself, for the purpose of matching `:toggle()`, `toggle-trigger`, `toggle-visibility`, etc.

An element can initialize its toggle sharing via CSS, but like toggles themselves, can't alter or remove them afterwards; you have to use JS to do that, via a new bit of API I'll define.

So here's how I anticipate it looking. First, here's the existing "alternating tabs" structure and style:

```html
<div class=tab-view>
  <div class=tab>foo</div>
  <div class=panel>foo content</div>
  <div class=tab>bar</div>
  <div class=panel>bar content</div>
</div>
<style>
.tab-view {
  toggle-group: --tab;
}
.tab {
  toggle: --tab;
}
.tab:first-of-type {
  toggle: --tab 1 at 1;
  /* first tab is open initially */
}
.panel {
  toggle-visibility: toggle --tab;
}
.tab:toggle(--tab) {
 font-weight: bold;
}
.panel:toggle(--tab) .spinner {
  animation: spin 1s infinite;
}
</style>
```

Here's how it would look in the "grouped tabs" structure:

```html
<div class=tab-view>
  <div class=tab-list>
    <div class=tab data-share="foo">foo</div>
    <div class=tab data-share="bar">bar</div>
  </div>
  <div class=panel-list>
    <div class=panel data-share="foo">foo content</div>
    <div class=panel data-share="bar">bar content</div>
  </div>
</div>
<style>
.tab-view {
  toggle-group: --tab;
}
.tab {
 toggle: --tab;
 toggle-share: attr(data-share) group --tab, --tab;
 /* share name (can be string or ident, to make attr() usage easier), 
     followed by group name, 
     then comma-separated list of toggle names to share */
}
.tab:first-of-type {
  toggle: --tab 1 at 1;
  /* first tab is open initially */
}
.panel {
  toggle-share: attr(data-share) group --tab;
  /* Share name and group name, but no toggles to add */
  toggle-visibility: toggle --tab;
}
.tab:toggle(--tab) {
 font-weight: bold;
}
.panel:toggle(--tab) .spinner {
  animation: spin 1s infinite;
}
</style>
```

So the tabs work as normal, each establishing their own 2-state `--tab` toggle, all grouped under the `--tab` group so only one is active at a time. But each also shares their `--tab` toggle under a unique author-chosen name, scoped under the `--tab` group. The panels then also opt into sharing with the same set of unique names, so they act as if they also contain the corresponding `--tab` toggle on themselves, so they can use it in `toggle-visibility` and select it in `:toggle()`.

------

The related scenario of a standard toggle that wants to be activatable from a random button elsewhere in the DOM works similarly:

```html
<spoiler- id=star-wars>
  <spoiler-warning>star wars spoiler</spoiler-warning>
  <spoiler-content>luke is his own father</spoiler-content>
</spoiler->
...
<button class=toggle data-for=star-wars>Show that Star Wars spoiler</button>

<style>
spoiler- {
  toggle-root: --spoiler;
  toggle-share: attr(id), --spoiler;
}
spoiler-warning {
  toggle-trigger: --spoiler;
}
spoiler-content {
  toggle-visibility: --spoiler;
}
button.toggle {
  toggle-share: attr(data-for);
  toggle-trigger: --spoiler;
}
</style>
```

Since there's no `group` in `toggle-share`, this is a global name (well, global to the tree scope; shadows would encapsulate this), so the button can target it from *wherever* as long as it matches the name.

-----

Some additional thoughts:

* Need to define how to resolve things when multiple elements share toggles with the same name. This is an error case, so just need a well-defined resolution algo, whatever's simplest for UAs. Probably first in tree order?
* Since strings are allowed, and `counter()` can produce incrementing unique strings associated with sibling index, in the  tabs example we could do some trickery to eliminate any need for the author to specify unique names, like:

	```css
	.tab-list, .panel-list {
	  counter-reset: toggle-i;
	}
	.tab, .panel {
	  counter-increment: toggle-i;
	}
	.tab {
	  toggle-share: counter(toggle-i) group --tab, --tab;
	}
	.panel {
	  toggle-share: counter(toggle-i) group --tab;
	}
	```

	Boom, unique names (just strings containing successive integers) that match across the two lists automatically. In theory this might be possible to do in a more "built-in" fashion as part of the Toggle spec itself, but it seems like there's enough complexity in it that it's probably not worthwhile.
* The API for toggle-share persistence would probably be something like a `.toggleShare` attribute, holding  a `CSSToggleShare` object that holds the share name, the group name, and the list of toggle names.

**Comment by bramus** [comment]
> First, here's the existing "alternating tabs" structure and style:
> 
> _[code block]_
> 
> Here's how it would look in the "grouped tabs" structure:
> 
> _[code block]_

What I don’t like about this second snippet it that it has a lot of duplication. The `.tab` toggle already opts into the group because it uses the same name `--tab`, but in your proposal it’s required to repeat all that info in the `toggle-share` attribute again:

```css
.tab-view {
  toggle-group: --tab;
}

.tab {
 toggle: --tab;
 toggle-share: attr(data-share) group --tab, --tab;
}

.panel {
  toggle-share: attr(data-share) group --tab;
  toggle-visibility: --tab;
}
```

What I derive from this example is that each toggle has a binary state (1 or 0) but also wants to represent a certain value in the group when toggled on. Would it be sufficient to only define that value? I’m thinking of a `toggle-value` property to do this, which would make things much more simpler.

```css
.tab-view {
  toggle-group: --tab;
}

.tab {
 toggle: --tab;
 toggle-value: attr(data-share);
}

.panel {
 toggle-visibility: --tab;
 toggle-value: attr(data-share);
}
```

The value for the toggle group is that of the active toggle in that group.

Maybe this `toggle-value` could also become part of the `toggle` and `toggle-visibility` shorthands?

```css
.tab-view {
  toggle-group: --tab; /* Establish group */
}

.tab {
 toggle: --tab attr(data-share); /* I am a toggle. When active, the value attr(data-share) becomes the value of the toggle-group I have opted into. */
}

.panel {
 toggle-visibility: --tab attr(data-share); /* I am visible/invisible when a toggle with the value attr(data-share) is active/inactive */
}
```

The spoiler toggle example would then become this:

```html
<spoiler-wrapper id=star-wars>
  <spoiler-warning>star wars spoiler</spoiler-warning>
  <spoiler-content>luke is his own father</spoiler-content>
</spoiler-wrapper>

<spoiler-wrapper id=star-trek>
  <spoiler-warning>star trek spoiler</spoiler-warning>
  <spoiler-content>Picard is Professor X</spoiler-content>
</spoiler-wrapper>

<button class=toggle data-for=star-wars>Show that Star Wars spoiler</button>
<button class=toggle data-for=star-trek>Show that Star Trek spoiler</button>
```

```css
spoiler-wrapper {
  toggle-root: --spoiler attr(id); /* Establish toggle root. When the toggle active, the value for the root is attr(id) */
}
spoiler-warning {
  toggle-trigger: --spoiler; /* Activates/deactivates the --spoiler toggle. Because of how scoping works, it’ll find the parent  spoiler-wrapper */
}
spoiler-content {
  toggle-visibility: --spoiler; /* I am visible/invisible when the toggle --spoiler is active/inactive */
}
button.toggle {
  toggle-trigger: --spoiler attr(data-for); /* Activates/deactivates the --spoiler toggle with the value attr(data-for). Because of how wide scoping works, it’ll find the spoiler-wrapper with the relevant toggle-root. */
}
```

---

A limitation I see with the above _(both your and my versions)_ is that it’s only possible to automatically respond to a certain toggle value using the `toggle-visibility` property. You can’t use the automated values in selectors.

```css
.panel:toggle(--tab foo) .spinner {
  animation: spin 1s infinite;
}
```

One could leverage the attribute that was set, but this breaks copy pasting.

```css
.panel[data-share="foo"]:toggle(--tab) .spinner {
  animation: spin 1s infinite;
}
```

But maybe this is an edge case, that should not be covered. I mean, if one wants to specially style a specific element they would already need a specific selector for it anyway, without toggles even coming into play.

---

> Since strings are allowed, and counter() can produce incrementing unique strings associated with sibling index, in the tabs example we could do some trickery to eliminate any need for the author to specify unique names

Yes! I like this! In the future `sibling-index()` could even further simplify the code.
