### ISSUE TITLE
bikeshed suggestion — `:checked` → `:toggled`

### ISSUE THREAD

**Issue by jonathantneal** [tabatkins/css-toggle#5]
I often think of `:checked` as exclusively having 2 states (_boolean_). Since CSS Toggles could be used to give meaning beyond 2 states (like [checked, unchecked, & indeterminate](https://tabatkins.github.io/css-toggle/#example-e6585699)), would you consider `:toggled` (or `:toggle`) as the [pseudo-selector name](https://tabatkins.github.io/css-toggle/#checked-pseudoclass)?

```css
.tristate-check {
  toggle: check 0/2;
}
.tristate-check:toggled(1) {
  /* "checked" styles */
}
.tristate-check:toggled(2) {
  /* "indeterminate" styles */
}
```

```css
.tristate-check {
  toggle: check 0/2;
}
.tristate-check:toggled(check 1) {
  /* "checked" styles */
}
.tristate-check:toggled(check 2) {
  /* "indeterminate" styles */
}
```
