### ISSUE TITLE
Feedback on the tristate check example, and a suggestion

### ISSUE THREAD

**Issue by jonathantneal** [tabatkins/css-toggle#6]
### Feedback

Currently, [Example 8](https://tabatkins.github.io/css-toggle/#example-e6585699) demonstrates how one could use CSS Toggles to design a checkbox with an "indeterminate" state.

I would expect this example to show me how my own check could toggle from "indeterminate" to "checked", and then between "checked" and "unchecked" indefinitely.

```css
.tristate-check {
	toggle: check 0/2;
}

.tristate-check:toggle(check 1) {
	/* "checked" styles */
}

.tristate-check:toggle(check 2) {
	/* "indeterminate" styles */
}
```

In this example, my understanding is that `0` specifies the **initial** state and `2` specifies the **maximum** state of my check.

However, because the next rules describe `1` as "checked" and `2` as "indeterminate", I think this means my check will cycle from "unchecked" (`0`) to "checked" (`1`) to "indeterminate" (`2`) and back to "unchecked" (`0`). This won’t work for me, because I want my initial state to be "indeterminate", and because I do not ever want to toggle from "checked" to "indeterminate".

With this (_potential misunderstanding of the spec_) in mind, I have tried to imagine the correct CSS using the spec.

```css
.tristate-check {
	toggle: check 0/2 sticky;
}

.tristate-check:toggle(check 0) {
	/* "indeterminate" styles */
}

.tristate-check:toggle(check 1) {
	/* "checked" styles */
}

.tristate-check:toggle(check 2) {
	/* "unchecked" styles */
}
```

In this example, my understanding is that `0` specifies the **initial** state, `2` specifies **maximum** state, and `sticky` specifies that my check will only cycle between the **active** states (`1` and `2`).

I think this will work for me. However, this might not work if I’m using a group, where `0` must be the "unchecked" state. (_Because `0` is inactive? Do I have that right?_)

### Suggestion

With that (_potentially deeper misunderstanding_) in mind, I have tried to imagine the correct CSS _inspired_ by the spec.

```css
.tristate-check {
	toggle: check 2 1 0 reverse;
}

.tristate-check:toggle(check 0) {
	/* "unchecked" styles */
}

.tristate-check:toggle(check 1) {
	/* "checked" styles */
}

.tristate-check:toggle(check 2) {
	/* "indeterminate" styles */
}
```

In this example, my understanding would be that `2` specifies the **initial** state, `1` the **maximum** state, `0` the **minimum** state, and `reverse` the **direction** incremented.

This would make more sense to me, because I think it means my check would toggle from "indeterminate" (`2`) to "checked" (`1`), and then between "checked" and "unchecked" (`0`) indefinitely. I would also expect this to work if I’m using a group. (_If `0` must be the "unchecked" state?_)

**Comment by jonathantneal** [comment]
I’m done editing now. Sorry for any confusion. It took me a few takes. ❤️

**Comment by davidkpiano** [comment]
IMO, while this technically solves the problem:

```css
.tristate-check {
	toggle: check 2 1 0 reverse;
}
```

There are some acrobatics involved with figuring out the right values to get the above to work, when in reality, you want to express it as a directed graph:

<img width="521" alt="CleanShot 2021-06-16 at 18 28 18@2x" src="https://user-images.githubusercontent.com/1093738/122302904-bfb8a280-ced0-11eb-8c74-f255a2378c61.png">

This also highlights a bigger concern: **linear sequencing is not sufficient** (even with cycles) for all potential use-cases, and this is an obvious one, so I love that @jonathantneal pointed it out!

It would be much more beneficial to have a way of representing the directed graph in CSS, with shorthands for common use-cases like sequences (with/without cycles), so the above use-case might look something like this:

```css
.tristate-check {
  toggle-transitions: 0 1, 1 2, 2 1;
}

# Or with names...
.tristate-check {
  toggle-transitions:
    indeterminate checked,
    checked unchecked,
    unchecked checked;
}
```

`toggle-transitions` is bike-sheddable (conflicts with CSS transitions, I know) but it represents the state transitions, or the _edges_ between the nodes in the digraph.

What do you think?
